### ISSUE TITLE
Feedback: great job and i'm willing to contribute at some point in near future.

### ISSUE THREAD

**Issue by timgluz** [marcliberatore/mallet-lda#1]
I found your library couple weeks ago from your blog when i was looking LDA libraries and preferable written in Clojure.

For Clojure there were only 2project: yours and deprecated [chisel](https://github.com/davidandrzej/chisel). 
And  your library exists on [VersionEye](http://www.versioneye.com/clojure/marcliberatore.mallet-lda:marcliberatore.mallet-lda/0.1.1), which makes it very easy to track new versions and dependencies.

 I decided to add more functionalities to make it more suitable for my next project.  You can check out current progress [on my fork](https://github.com/timgluz/mallet-lda). 

 I'm currently working on model's serialization and i'm also going to add some simple tests on this weekend.

Is there better Mallet's documentation? Or does researcher at Amhart also have to use that ugly JavaDoc? 

I'm not researcher myself, all my knowledge about LDA comes from [this paper here](http://www.cs.princeton.edu/~blei/papers/BleiNgJordan2003.pdf).  With my limited knowledge is quite difficult de-cipher what some methods are doing and write user-friendly doc-string. 

Should i start bombing mail-list question-by-questions until they'll see benefits of having decent documentation? :d sounds like great hobby. 

Ok, back to hacking.

**Comment by marcliberatore** [comment]
I took a look at your fork, and it looks good. When you think you're at a good spot you should let me know, and we should integrate my code and yours.

There is not, to my knowledge, better Mallet documentation than the javadoc and tutorials at http://mallet.cs.umass.edu/

Different pieces of Mallet were authored by different people, and the relative importance they placed on good documentation varied. Some of them have since left (graduated, new job, etc.) and I'm not sure how much they monitor the mailing list. I'm happy to help write docstrings, but I am definitely not a topic modeling expert, either, so I may not be able to do much better than you.

I'm quite busy for the next couple weeks. After they are over I will be glad to pick this project back up.

Again, great work on the fork!

**Comment by timgluz** [comment]
Great.
I think i'll be ready for merging next week;

I'm going to use my fork this week in my project and let's see how it works with real data.
